package eggsky.game;

import eggsky.Game;
import eggsky.core.Rng;
import eggsky.world.StarSystem;
import java.util.ArrayList;
import java.util.List;

/**
 * The Egg Station's mission board. Each station offers three jobs, regenerated by system and by
 * how far the expedition has come; Eggman takes one at a time. A mission is stored as eight
 * numbers: type, item, count, the statistic's value when accepted, ring reward, shard reward,
 * bonus item and its count.
 */
public final class Missions {
    public static final int DELIVER = 0;
    public static final int SURVEY = 1;
    public static final int REPEL = 2;
    public static final int PIRATES = 3;
    public static final int MINE = 4;
    public static final int EXPLORE = 5;

    private Missions() {
    }

    public static List<long[]> offers(Game g, StarSystem s) {
        Player p = g.player;
        Rng rng = new Rng(Rng.hash(s.seed, 0x4D495353L, p.statWarps * 31L + p.visitedSystems.size()));
        List<long[]> out = new ArrayList<>();
        int[] deliverable = {Catalog.CARBON, Catalog.FERRITE, Catalog.OXYGEN, Catalog.SODIUM, Catalog.DIHYDROGEN,
                Catalog.PURE_FERRITE, Catalog.CONDENSED_CARBON, Catalog.CHROMATIC_METAL, Catalog.COBALT, Catalog.GOLD,
                Catalog.BADNIK_SCRAP};
        int tier = 1 + p.statWarps / 3;
        for (int i = 0; i < 3; i++) {
            int type = rng.nextInt(6);
            long item = 0;
            long count;
            long base;
            switch (type) {
                case DELIVER -> {
                    item = deliverable[rng.nextInt(deliverable.length)];
                    count = rng.range(20, 60) + tier * 10L;
                    base = 0;
                }
                case SURVEY -> {
                    count = rng.range(3, 6);
                    base = p.statSpecies;
                }
                case REPEL -> {
                    count = rng.range(2, 5);
                    base = p.statSonicRepelled;
                }
                case PIRATES -> {
                    count = rng.range(2, 5);
                    base = p.statPirates;
                }
                case MINE -> {
                    count = rng.range(25, 60);
                    base = p.statMined;
                }
                default -> {
                    count = rng.range(1, 3);
                    base = p.statPlanets;
                }
            }
            long rings = (type == DELIVER ? count * (long) Math.max(10, g.catalog.item((int) item).value()) * 2
                    : 600L * count / Math.max(1, type == MINE ? 10 : 1)) + tier * 150L;
            long shards = 20 + rng.nextInt(30) + tier * 8L;
            long bonus = 0;
            long bonusCount = 0;
            if (rng.chance(0.3)) {
                bonus = rng.chance(0.5) ? Catalog.WARP_CELL : Catalog.ANTIMATTER;
                bonusCount = 1;
            }
            out.add(new long[] {type, item, count, base, rings, shards, bonus, bonusCount});
        }
        return out;
    }

    public static String describe(Game g, long[] m) {
        int count = (int) m[2];
        return switch ((int) m[0]) {
            case DELIVER -> "Deliver " + count + " " + g.catalog.name((int) m[1]) + " to any Egg Station";
            case SURVEY -> "Analyse " + count + " new species";
            case REPEL -> "Repel " + count + " of Sonic's friends";
            case PIRATES -> "Destroy " + count + " pirate ships";
            case MINE -> "Mine or harvest " + count + " deposits";
            default -> "Land on " + count + " new planet" + (count > 1 ? "s" : "");
        };
    }

    public static String reward(Game g, long[] m) {
        String s = Long.toString(m[4]) + " rings, " + m[5] + " shards";
        if (m[6] != 0) {
            s += ", " + m[7] + " " + g.catalog.name((int) m[6]);
        }
        return s;
    }

    /** Progress toward the count. */
    public static int progress(Game g, long[] m) {
        Player p = g.player;
        long now = switch ((int) m[0]) {
            case DELIVER -> p.cargo.count((int) m[1]);
            case SURVEY -> p.statSpecies;
            case REPEL -> p.statSonicRepelled;
            case PIRATES -> p.statPirates;
            case MINE -> p.statMined;
            default -> p.statPlanets;
        };
        return (int) Math.max(0, Math.min(m[2], now - m[3]));
    }

    public static long[] active(Player p) {
        if (p.missions == null || p.missions.isEmpty()) {
            return null;
        }
        String[] parts = p.missions.split(":");
        if (parts.length < 8) {
            return null;
        }
        long[] m = new long[8];
        try {
            for (int i = 0; i < 8; i++) {
                m[i] = Long.parseLong(parts[i]);
            }
        } catch (NumberFormatException bad) {
            return null;
        }
        return m;
    }

    public static void accept(Player p, long[] m) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 8; i++) {
            sb.append(i > 0 ? ":" : "").append(m[i]);
        }
        p.missions = sb.toString();
    }

    public static String describeActive(Game g) {
        long[] m = active(g.player);
        if (m == null) {
            return null;
        }
        return describe(g, m) + " (" + progress(g, m) + "/" + m[2] + ")";
    }

    public static boolean complete(Game g, long[] m) {
        return progress(g, m) >= m[2];
    }

    /** Hands in the active mission; returns the reward text, or null when not finished. */
    public static String handIn(Game g) {
        Player p = g.player;
        long[] m = active(p);
        if (m == null || !complete(g, m)) {
            return null;
        }
        if (m[0] == DELIVER) {
            p.cargo.remove((int) m[1], (int) m[2]);
        }
        p.rings += m[4];
        p.statRingsEarned += m[4];
        p.shards += (int) m[5];
        if (m[6] != 0) {
            p.cargo.add((int) m[6], (int) m[7]);
        }
        p.missions = "";
        return reward(g, m);
    }
}
