#!/usr/bin/env python3
"""Build the racing server tools (master, dedicated host, verifier, bot/load/profile tools).

Usage:
  python3 racing/server/build.py                  # compile into target/racing-server/
  python3 racing/server/build.py --skip-engine    # reuse the engine build already in target/
  target/racing-server/racing-server master --config master.yaml
  target/racing-server/racing-server verifier --master https://host:27900 --registration-token T --rom s3k.gen --data ./verifier-data
  target/racing-server/racing-server load-test --n 256 --duration 30 --mix adversarial

The server is not part of the engine artifact. It compiles the racing library
(racing/time-attack) and racing/server against the engine build, with Netty, Bouncy Castle and
SQLite from the engine's test-scoped dependencies, and writes a launcher whose classpath points at
target/classes, the compiled racing classes and the resolved dependency jars. The verifier embeds
the engine to replay attempts, so the engine build must match the clients' engine.

Origin: Time Attack extraction (docs/architecture/plans/2026-10-08-time-attack-mod-extraction.md).
"""
import argparse
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "target" / "racing-server"
TOOLS = {
    "master": "openggf.racing.server.master.MasterServerMain",
    "verifier": "openggf.racing.server.verifier.VerifierMain",
    "bot": "openggf.racing.server.tools.BotClient",
    "load-test": "openggf.racing.server.tools.GhostLoadTestTool",
    "track-profiles": "openggf.racing.server.tools.TrackProfileExportTool",
}


def java_tool(tool):
    home = os.environ.get("JAVA_HOME")
    suffix = ".exe" if os.name == "nt" else ""
    return str(Path(home) / "bin" / (tool + suffix)) if home else tool


def build(skip_engine=False):
    classpath_file = ROOT / "target" / "racing-server-classpath.txt"
    if not skip_engine or not classpath_file.exists():
        subprocess.run([sys.executable, "tools/testing/maven_queue.py", "-B", "-q", "-Dmse=off", "-DskipTests",
                        "compile", "dependency:build-classpath", "-Dmdep.includeScope=test",
                        f"-Dmdep.outputFile={classpath_file}"], cwd=ROOT, check=True)
    classes = OUT / "classes"
    if classes.exists():
        shutil.rmtree(classes)
    classes.mkdir(parents=True)
    deps = classpath_file.read_text().strip()
    compile_cp = os.pathsep.join([str(ROOT / "target" / "classes"), deps])
    sources = sorted(str(p) for root in ("racing/time-attack/src/main/java", "racing/server/src/main/java")
                     for p in (ROOT / root).rglob("*.java"))
    subprocess.run([java_tool("javac"), "--release", "21", "-nowarn", "-cp", compile_cp, "-d", str(classes),
                    *sources], check=True)
    shutil.copytree(ROOT / "racing/server/src/main/resources", classes, dirs_exist_ok=True)
    runtime_cp = os.pathsep.join([str(classes), str(ROOT / "target" / "classes"), deps])
    (OUT / "java-args.txt").write_text('-cp "' + runtime_cp.replace("\\", "/") + '"\n')
    if os.name == "nt":
        print(f"Built {classes}; run a tool with: java @{OUT / 'java-args.txt'} <main class> [args...]")
        return
    launcher = OUT / "racing-server"
    cases = "\n".join(f'  {name}) main={main} ;;' for name, main in TOOLS.items())
    launcher.write_text(f"""#!/bin/sh
# Generated by racing/server/build.py. Usage: racing-server <{'|'.join(TOOLS)}> [args...]
tool="$1"; shift
case "$tool" in
{cases}
  *) echo "usage: racing-server <{'|'.join(TOOLS)}> [args...]" >&2; exit 2 ;;
esac
exec "{java_tool('java')}" -cp "{runtime_cp}" "$main" "$@"
""")
    launcher.chmod(0o755)
    print(f"Built {launcher}", flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--skip-engine", action="store_true", help="reuse the existing engine build in target/")
    build(parser.parse_args().skip_engine)


if __name__ == "__main__":
    main()
