package example.platformer;

import com.openggf.io.ModAssetRoot;
import com.openggf.level.Level;
import com.openggf.level.Pattern;
import com.openggf.level.objects.BakedSheetReader;
import com.openggf.level.objects.PlayableSheetMaterializer;
import com.openggf.level.rings.RingFrame;
import com.openggf.level.rings.RingFramePiece;
import com.openggf.level.rings.RingSpriteSheet;
import com.openggf.mods.code.BakedLevelRef;
import com.openggf.mods.code.BakedSheetRef;
import com.openggf.mods.code.GgfMod;
import com.openggf.mods.code.ModContext;
import com.openggf.mods.code.StandaloneLevelLoader;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.List;

public final class PlatformerMod implements GgfMod {
    @Override
    public void register(ModContext context) {
        try {
            ModAssetRoot assets = context.modAssets();
            var materialized = PlayableSheetMaterializer.read(
                    assets.readBounded("art/bolt.ggfp", assets.limits().maxAssetBytes()));
            Level level = StandaloneLevelLoader.load(assets,
                    new BakedLevelRef("levels/act1/level.json"), context.ownerModId(),
                    buildRingSheet(assets));
            context.registerObject("zapbug", (spawn, registry) -> new ZapBug(spawn));
            context.registerObjectArt("zapbug", new BakedSheetRef("art/zapbug.ggfs"));
            context.registerObject("springpad", (spawn, registry) -> new SpringPad(spawn));
            context.registerObjectArt("springpad", new BakedSheetRef("art/springpad.ggfs"));
            context.registerCharacter("bolt", BoltCharacter.definition(
                    context.ownerModId(), materialized));
            context.registerGameModule(new PlatformerModule(context.ownerModId(), level));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Reads {@code art/ring.ggfs} (generated by {@code SamplePlatformerAssetGenerator}'s
     * {@code ring.png} + {@code ring-sheet.yaml}, converted with plain {@code convert art})
     * into a real 6-arg {@link RingSpriteSheet}. Unlike the phase-3 sample -- whose level has
     * no rings and passes an empty sheet -- this level places ~20 ring markers, so the sheet
     * must carry real patterns and frames.
     */
    private static RingSpriteSheet buildRingSheet(ModAssetRoot assets) throws IOException {
        BakedSheetReader.BakedSheet sheet = BakedSheetReader.read(
                assets.readBounded("art/ring.ggfs", assets.limits().maxAssetBytes()));
        List<RingFrame> frames = sheet.frames().stream()
                .map(frame -> new RingFrame(frame.mapping().pieces().stream()
                        .map(piece -> new RingFramePiece(piece.xOffset(), piece.yOffset(),
                                piece.widthTiles(), piece.heightTiles(), piece.tileIndex(),
                                piece.hFlip(), piece.vFlip(), piece.paletteIndex()))
                        .toList()))
                .toList();
        int paletteLine = sheet.palette().map(BakedSheetReader.Palette::line).orElse(0);
        int frameDelay = sheet.frames().isEmpty() ? 6 : sheet.frames().getFirst().delay();
        return new RingSpriteSheet(sheet.patterns(), frames, paletteLine, frameDelay,
                frames.size(), 0);
    }
}
