package com.openggf.game.sonic2.specialstage;

import java.util.Map;

/**
 * Stateless approximation of the Mega Drive lag observed in the Sonic 2
 * special stage. The bucket ratios are regenerated by
 * {@code Sonic2SpecialStageLagModelValidationTest} from the committed stage-1
 * trace and its ROM track layout.
 */
public final class Sonic2SpecialStageLagModel {
    private static final Map<Bucket, BucketRatio> TRACE_BUCKETS = Map.of(
            new Bucket(0, 12), new BucketRatio(65, 185),
            new Bucket(1, 12), new BucketRatio(82, 202),
            new Bucket(2, 12), new BucketRatio(297, 837),
            new Bucket(3, 0), new BucketRatio(104, 126),
            new Bucket(3, 12), new BucketRatio(1121, 3152),
            new Bucket(4, 12), new BucketRatio(302, 797));
    private static final BucketRatio FALLBACK_RATIO = new BucketRatio(1971, 5299);

    private Sonic2SpecialStageLagModel() {
    }

    /**
     * Returns whether this host frame is a simulated hardware lag frame.
     *
     * <p>The threshold sequence is a stateless Bresenham-style distribution:
     * the same five runtime inputs always produce the same result, so rewind
     * needs no additional pacing state.</p>
     */
    public static boolean shouldLagThisFrame(
            int frameCounter,
            int speedFactor,
            int segmentType,
            int drawingIndex,
            int liveObjectCount) {
        BucketRatio ratio = ratioForBucket(segmentType, speedFactor);
        // The committed recorder captures drawingIndex but not liveObjectCount.
        // Keep both inputs in the stable API for future multi-trace calibration,
        // but do not let unvalidated load proxies silently retune this fit.
        long phase = Math.floorMod((long) frameCounter * ratio.numerator(), ratio.denominator());
        return phase < ratio.numerator();
    }

    static BucketRatio ratioForBucket(int segmentType, int speedFactor) {
        return TRACE_BUCKETS.getOrDefault(new Bucket(segmentType, speedFactor), FALLBACK_RATIO);
    }

    record BucketRatio(int numerator, int denominator) {
        BucketRatio {
            if (numerator < 0 || denominator <= 0 || numerator > denominator) {
                throw new IllegalArgumentException("invalid lag ratio " + numerator + "/" + denominator);
            }
        }

        double fraction() {
            return numerator / (double) denominator;
        }
    }

    private record Bucket(int segmentType, int speedFactor) {
    }
}
