#!/usr/bin/env python3
"""Compile/package exported Java examples using matching candidate artifacts.

Inputs are a project and absolute engine/SDK jar paths. No engine checkout, ROM
links, downloaded assets or Maven publication is needed. Origin: creator readiness
2026-10-07. Runtime configuration lives in target/play and never changes user config.
"""
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import zipfile


def matching_artifacts(engine, sdk, testkit=None):
    identities = []
    artifacts = [(engine, "version.properties"), (sdk, "META-INF/openggf-build.properties")]
    if testkit:
        artifacts.append((testkit, "META-INF/openggf-build.properties"))
    for artifact, identity_path in artifacts:
        with zipfile.ZipFile(artifact) as archive:
            identities.append(dict(line.split("=", 1) for line in archive.read(identity_path).decode().splitlines()
                                   if "=" in line and not line.startswith("#")))
    if any(identity != identities[0] for identity in identities[1:]):
        raise ValueError("Engine, SDK and optional testkit must come from the same candidate build")
    if not identities[0].get("app.commit") or "${" in identities[0]["app.commit"]:
        raise ValueError("Candidate artifacts must record their source commit")
    return identities[0]


def java_tool(name):
    home = os.environ.get("JAVA_HOME")
    return str(Path(home) / "bin" / (name + (".exe" if os.name == "nt" else ""))) if home else name


def runtime_directory(project, roms):
    play = Path(project) / "target/play"
    play.mkdir(parents=True, exist_ok=True)
    config = 'configFormat: 2\nroms:\n  directory: "roms"\n'
    for key in ("sonic1", "sonic2", "sonic3k"):
        value = (roms or {}).get(key)
        if value is not None:
            value = Path(value).resolve(strict=True)
            if not value.is_file():
                raise ValueError(f"ROM is not a file: {value}")
        config += f"  {key}: {json.dumps(str(value) if value else '')}\n"
    (play / "config.yaml").write_text(config, encoding="utf-8")
    return play


def build(project, engine, sdk, *, run=False, roms=None, testkit=None):
    project, engine, sdk = (Path(p).resolve() for p in (project, engine, sdk))
    for artifact in (engine, sdk):
        if not artifact.is_file():
            raise ValueError(f"Missing matching creator artifact: {artifact}")
    matching_artifacts(engine, sdk, testkit)
    if not (project / "src/main/resources/META-INF/openggf-mod.yaml").is_file():
        raise ValueError(f"No mod manifest in project: {project}")
    classes = project / "target/classes"
    if classes.exists():
        shutil.rmtree(classes)
    classes.mkdir(parents=True)
    classpath = os.pathsep.join(map(str, (engine, sdk)))
    sources = sorted((project / "src/main/java").rglob("*.java"))
    if sources:
        subprocess.run([java_tool("javac"), "--release", "21", "-cp", classpath,
                        "-d", str(classes), *map(str, sources)], check=True)
    shutil.copytree(project / "src/main/resources", classes, dirs_exist_ok=True)
    cli = [java_tool("java"), "-cp", classpath, "com.openggf.tools.modsdk.GgfModCli"]
    jar = project / "target" / (project.name + "-mod.jar")
    jar.unlink(missing_ok=True)
    subprocess.run([*cli, "package", "--input", str(classes), "--out", str(jar)], check=True)
    if run:
        # This directory is exclusively generated by this launcher; JSON strings
        # are valid YAML strings and safely preserve spaces/Windows separators.
        subprocess.run([*cli, "run", str(classes)], cwd=runtime_directory(project, roms), check=True)
    return jar


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path)
    kit = Path(__file__).resolve().parent.parent
    parser.add_argument("--engine", type=Path, default=kit / "engine.jar")
    parser.add_argument("--sdk", type=Path, default=kit / "sdk.jar")
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--testkit", type=Path, help="verify an optional matching testkit before local test setup")
    parser.add_argument("--verify-only", action="store_true", help="verify artifact version/source identity without compiling")
    for name in ("s1", "s2", "s3k"):
        parser.add_argument("--" + name, type=Path)
    args = parser.parse_args(argv)
    if args.verify_only:
        print(json.dumps(matching_artifacts(args.engine, args.sdk, args.testkit), sort_keys=True))
        return
    print(build(args.project, args.engine, args.sdk, run=args.run,
                roms=dict(zip(("sonic1", "sonic2", "sonic3k"), (args.s1, args.s2, args.s3k))), testkit=args.testkit))


if __name__ == "__main__":
    main()
