package com.openggf.game.rewind.snapshot;

import com.openggf.level.Block;
import com.openggf.level.Chunk;
import com.openggf.level.Pattern;
import com.openggf.game.CheckpointState;

/**
 * Reference-only level snapshot. Block/Chunk/Pattern arrays are shared while
 * the level is unchanged; gameplay mutation surfaces replace the live array and
 * edited entry before writing so captured snapshots keep the old structure.
 * mapData is the Map's underlying byte[]; CoW in Map.cowEnsureWritable clones
 * it on the first gameplay-path mutation per epoch, so snapshot keeps the old
 * ref.
 *
 * Most pattern bytes are derived state regenerated by animator counters on the
 * next forward step. The exception is runtime pattern-overlay edits
 * (Sonic3kLevel.applyPatternOverlay, e.g. AIZ2 battleship terrain at tile
 * 0x1FC and the fire overlay at tile 0x500): those overwrite live pattern
 * pixels and the GL atlas in place and are NOT regenerated by animator
 * counters, so a rewind that crosses such an overlay would otherwise leave the
 * overlay pixels behind. applyPatternOverlay now clones the patterns array
 * copy-on-write (fresh Pattern instances for touched slots) so this snapshot's
 * captured array keeps the pre-overlay pixels; restore swaps the array back and
 * re-caches only the changed atlas slots.
 *
 * frameCounter is LevelManager.frameCounter: the per-frame counter passed
 * into ObjectManager.update / RingManager.collectStageRings /
 * OscillationManager.update. Without restoring it, vbla-mod-8 badnik AI
 * timing gates fire at different absolute frames after rewind, cascading
 * into divergent badnik / ring / oscillation state on the very first
 * post-restore step.
 */
public record LevelSnapshot(
        long epochAtCapture,
        Block[] blocks,
        Chunk[] chunks,
        Pattern[] patterns,
        byte[] mapData,
        int frameCounter,
        boolean hasLevelHudState,
        int levelRings,
        long levelTimerFrames,
        boolean levelTimerPaused,
        boolean respawnRequested,
        CheckpointState.RewindState checkpointState) {

    public LevelSnapshot(
            long epochAtCapture,
            Block[] blocks,
            Chunk[] chunks,
            Pattern[] patterns,
            byte[] mapData,
            int frameCounter) {
        this(epochAtCapture, blocks, chunks, patterns, mapData, frameCounter,
                false, 0, 0, false, false, null);
    }

    public LevelSnapshot(
            long epochAtCapture,
            Block[] blocks,
            Chunk[] chunks,
            Pattern[] patterns,
            byte[] mapData,
            int frameCounter,
            boolean respawnRequested) {
        this(epochAtCapture, blocks, chunks, patterns, mapData, frameCounter,
                false, 0, 0, false, respawnRequested, null);
    }
}
