package com.openggf.game.patch;

import java.util.Objects;

/** Immutable owner-tagged patch contribution in a frozen launch plan. */
@com.openggf.game.ModApi
public final class RegisteredPatch {

    private final PatchOwner owner;
    private final String namespacedId;
    private final GamePatch patch;
    private final long registrationIndex;
    private final boolean engineGeneratedDecoratorOnly;

    public RegisteredPatch(PatchOwner owner, String namespacedId,
            GamePatch patch, long registrationIndex) {
        this(owner, namespacedId, patch, registrationIndex, false);
    }

    private RegisteredPatch(PatchOwner owner, String namespacedId,
            GamePatch patch, long registrationIndex, boolean engineGeneratedDecoratorOnly) {
        this.owner = Objects.requireNonNull(owner, "owner");
        this.namespacedId = requireNonBlank(namespacedId, "namespacedId");
        this.patch = Objects.requireNonNull(patch, "patch");
        if (registrationIndex < 0) {
            throw new IllegalArgumentException("registrationIndex must be non-negative");
        }
        this.registrationIndex = registrationIndex;
        this.engineGeneratedDecoratorOnly = engineGeneratedDecoratorOnly;
    }

    /**
     * Marks a patch whose implementation is generated by the engine and known to
     * decorate without mutating its input. Package-private so creator registrations
     * cannot opt themselves into last-good continuation.
     */
    static RegisteredPatch engineGeneratedDecorator(PatchOwner owner, String namespacedId,
            GamePatch patch, long registrationIndex) {
        return new RegisteredPatch(owner, namespacedId, patch, registrationIndex, true);
    }

    public PatchOwner owner() {
        return owner;
    }

    public String namespacedId() {
        return namespacedId;
    }

    public GamePatch patch() {
        return patch;
    }

    public long registrationIndex() {
        return registrationIndex;
    }

    boolean engineGeneratedDecoratorOnly() {
        return engineGeneratedDecoratorOnly;
    }

    private static String requireNonBlank(String value, String name) {
        Objects.requireNonNull(value, name);
        if (value.isBlank()) {
            throw new IllegalArgumentException(name + " must not be blank");
        }
        return value;
    }
}
